### ISSUE TITLE
As a Safety Driver, I want to see a checklist for the interior inspection.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-app#15]
**Back-end twin:**
TU-CP18/cp18-daimler-backend#29

**Description:**
After opening the car via the app the checklist for the interior inspection will be shown. The safety driver can start the ride only after he/she has checked all items.

**Acceptance criteria:**

- [x] A checkbox to confirm the interior operational readiness must be visible
- [x] The ride can only be started after the checkbox has been checked, the must be visualized as *disabled* accordingly
- [x] The checklist cannot be skipped
