### ISSUE TITLE
As a Safety Driver, I want to see a checklist for the exterior inspection.

### ISSUE THREAD

**Issue by calvinschmidt** [TU-CP18/cp18-app#22]
**Back-end twin:**

TU-CP18/cp18-daimler-backend#36

**Description:**
The safety driver should be able to see a checklist for exterior of the car. The items must be checked to proceed.

**Acceptance criteria:**

- [x] A checklist for the rear, driver, front and co-driver side must be visible
- [x] The checklist items can be checked/unchecked
- [x] The car can only be opened when the safety driver has checked all items
- [x] The safety driver can not skip this exterior check
