### ISSUE TITLE
Issue Tracking internal (FM+SD)

### ISSUE THREAD

**Issue by nschoen** [TU-CP18/cp18-app#42]
**Back-end twin:**

**Description:**
As a Safety Driver, I want to record issues with the vehicle interior.
The safety driver can record new issues by selecting the affected part of the car and provide a description.

**Acceptance criteria:**

- [x] The side (front, rear, driver, co-driver) of the car can be selected where the discovered issue belongs to
- [x] The affected area can be selected in a visualization of the car
- [x] A description can be entered
- [x] When submitting the new issue, it is communicated to the backend
- [x] A success message is visible when the issue has been created successfully 
- [x] The issue list is updated after the issues has been created successfully
- [x] An error message is visible when the issue could not be created
